apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CPfS81bIp1XAhO67oysVqlg=,iv:abqyEOD0wXSL2ysXlyvkyx2PRdLsfM9Te6cC5v/ZNrw=,tag:bNija49SyS1DwY/4pLa+KA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:+x73vlbaVOP5/YtFZaWThf1YkvO4jRaiBVq7AHPcbYJkERKVVA==,iv:BYf2HsBg1KZV4NZXaObBmZTQ2eOOApwx1Fi7i9YzWU4=,tag:jeXrvZ3/6cTFpGomktq3CA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:XS/JbKx5n/9p3MQwdQx6gY4=,iv:BpRLDZB7sl4G7SkDRLEYAILfIsIv7Eobe2mWanjk+lg=,tag:0JpqxarcqKF+Ei2Y0/u9CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zkfzu5mdxe390z2q0ud84vyhkhu7cjxh8zqeprddjn3e70l029vsmt4sye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdHZLUTVycmhWUjhwWVU2
            Zlo3V0NlOUJxamRCTUppWjNOTVplTGxCQW5RCjQ2REljNzVCd0Rjb3M5VVRuVmtp
            Z0VWczJyZkxyd1o5SUtYdE1IMnJWZXcKLS0tIGk4N1hLaUtGaDB2RVdwSi9kSjlP
            RFdGb0s1dGtpRUNJV2hCOVdnNStveTgKHmo7B8NWzFfGW4+VKD5tMyv26aO+Iotz
            ZGDWufLO9epF27j8djh1FYNsV4gcuiFEek9fnB6IpP2PyT7WXh+r/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T21:30:44Z"
    mac: ENC[AES256_GCM,data:gPqPT54Pl5J6NsbdSPSf/G/70UXIFlDHom/v+bUa/RkZ6JcdZXa4li/VcaSsLRsfYK2xnBvGU4L24e72bhvDbxoc6g9IBdtzhq0f1nfaz7q12jcBP/M+uP3rFfsnJLIA+qZa1eQAdtIM2Pcv6ROGqSg6PaI0F+Vuv2eqWteDx2c=,iv:oBc6ACt20wV9mZXveQFASVuTUQa9UWbeWQPpLh8u00s=,tag:M4LhJDaqGUfsbRGvHYR/ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
