---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: networking
  labels:
    app.kubernetes.io/name: cloudflared
  annotations:
    reloader.stakater.com/match: "true"
data:
  config.yaml: |
    tunnel: 27e57dab-d197-4349-8352-d8c2dab3ff7a
    credentials-file: /etc/cloudflared/cred.json
    no-autoupdate: true
    ingress:
    - hostname: "*.${SECRET_DOMAIN}"
      service: http://ingress-nginx-controller.networking
    - service: http_status:404
