---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-zigbee2mqtt-app
  namespace: flux-system
spec:
  dependsOn:
    - name: onedr0p-apps-mosquitto
  path: ./kubernetes/apps/default/zigbee2mqtt/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: zigbee2mqtt
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
