---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.30.3
    env:
      TZ: "${TIMEZONE}"
      ZIGBEE2MQTT_DATA: &path /config
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
      ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
      ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info # debug
      ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
      ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: 6969
      ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: '[11, 8, 2, 4, 7, 4, 2, 0, 6, 9, 3, 14, 15, 9, 6, 6]'
      ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
      ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000
      ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
      ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
      ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
      ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 80
      ZIGBEE2MQTT_CONFIG_FRONTEND_URL: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
      ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
      ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
      ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
      ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
      ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto.default.svc.cluster.local
      ZIGBEE2MQTT_CONFIG_MQTT_USER: admin
      ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: admin
      ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
      ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
      ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: 115200
      ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: "false"
      ZIGBEE2MQTT_CONFIG_SERIAL_PORT: &serial /dev/ttyUSB0
      ZIGBEE2MQTT_CONFIG_DEVICES: devices.yaml
      ZIGBEE2MQTT_CONFIG_GROUPS: groups.yaml
    service:
      main:
        ports:
          http:
            port: *port
    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: *serial
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:zigbee
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    securityContext:
      privileged: true
    volumeClaimTemplates:
      - name: config
        mountPath: *path
        accessMode: ReadWriteOnce
        size: 1Gi
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
