apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:h99pg5fnSq8xaAzApRiVY7qRVyd/dMCIg9yltMzSly1ARqtN63VNTg==,iv:CNaV1XoUximrs5x3kudRMOwdIlEfY1CHTyFOzHjOXxQ=,tag:cIlmLgBbHDaOC5JB28xZJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zkfzu5mdxe390z2q0ud84vyhkhu7cjxh8zqeprddjn3e70l029vsmt4sye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdWE2aTRVK3h0TmNRRkVC
            LzdnSFRiQ3RwY2E2ZHd2LzJkNC9FNUpic3hNCm0vWittR3ZRSXQyL0thQkprVE5F
            WWpCeXJWaFJMblk5dXdCV3RPUkZCWE0KLS0tIDRlRFQwNW13NWFNTzFsWDQrKy9r
            a3VtMXFTK0tUY21GQnNBd1V3RVRYRHcKPCcfSDLiuYRiLgDXmoKXEYrQKY8fQeRJ
            4Hl3kBBhQapAOzZiH17HC/7oPoWY1PPO7UvOa0wVqi3Ei+endz6DKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T21:30:44Z"
    mac: ENC[AES256_GCM,data:gF7xsocNs5aj9wEQk2W/gGDqSKPI9/mBIpJd3Qy/cCa6Cgrvcby0h7svV8+UtsvG6YRwDxFtnC9YS/5gr+9QtdjmW5lUsaftSFDwa8ktVmq8fV+zDsg3SFeknNzM0vziiqG+vrB3I8M7j4liErkjn5wK6mle2qlHrm72AEtxty4=,iv:mkEem/xvv0Llt4c6iJ+0AKNAvLNWgKzespzDJyDVmmw=,tag:4PW1KbvKEQwDe2wTZsK1gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
