---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx
      version: 5.0.23
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: public.ecr.aws/emqx/emqx
    replicaCount: 1
    recreatePods: true
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "true"
    service:
      type: LoadBalancer
      externalIPs: ["${SVC_EMQX_ADDR}"]
      externalTrafficPolicy: Local
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: "EMQX"
          hajimari.io/icon: simple-icons:eclipsemosquitto
        path: /
        pathType: Prefix
        hosts:
          - &host "emqx.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
    metrics:
      enabled: false
    persistence:
      enabled: true
      size: 100Mi
