apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:JNhmsIJpPdIULujW,iv:ID4PhCcQ8loQMYTl+ZBjpanOT+V5DZWRLONLz+JL/w0=,tag:IMRK6FdrZ7J6SveKgM6r4w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:QtUQQ8aCFmoPmO682RAd0WY=,iv:YPAj1BL9ZZQ9Ei0OBFm8UcBf4fQF2gKCUfWIFf9NBH0=,tag:VbQ4/Nt1QgqufBHhipYASw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zkfzu5mdxe390z2q0ud84vyhkhu7cjxh8zqeprddjn3e70l029vsmt4sye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaDhlMS9zU0E0djh5dzJi
            UkdmcEtlMzNBdDlPY0lIQkxUVzZrZnhoaUNJCjkyMVFhQ1UyRmtnTkF5YWN3NlpH
            SlVOaWViekRXOGFoQTkzQlBMQzNoTHcKLS0tIE9uYzd4M3o2a1JCQTJsakZuN1E1
            eFp3NDNVUTBhUTFUQzFyblNZN0tHU3cKKPi4/MedfKdH1qp2lKIRz07xYKAGDMPO
            AdClB3Ew7hmBJGgcUCILcQEyva0KaB+9NPdC8vyXmsmtgOul1PL8Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T21:30:44Z"
    mac: ENC[AES256_GCM,data:a/S65SCeYxoRH3/HxaxLl/3KVOI7xTtz2pyv4tU0ZbvFXZF7N+jJd472QbhJ6KcBnOBa6ykYcRI5NMcRPxr6TTI3C8XwRfoWm3n+Zhe5XB+AtNxM2O7HHioCCuLSd9SENFwsBiAzW3YIitfXvwn/QNKSdQky8krC81mbDpKc958=,iv:n3xL3YqxmL3CJgEoTWCjDkOVBO9gS/R+KXmVb6bcGKo=,tag:piWryS/MTo3w8RxJx3dIkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
