---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/London"
  KUBE_VIP_ADDR: "192.168.68.254"
  METALLB_LB_RANGE: "192.168.68.220-192.168.68.230"
  METALLB_K8S_GATEWAY_ADDR: "192.168.68.220"
  METALLB_INGRESS_ADDR: "192.168.68.221"
  SVC_HOME_ASSISTANT_ADDR: "192.168.68.222"
  SVC_EMQX_ADDR: "192.168.68.223"
