---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ispy
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: grinco/ispyagentdvr
      tag: 4.4.6.0
    hostNetwork: true
    service:
      main:
        type: LoadBalancer
        externalIPs: ["${SVC_ISPY_ADDR}"]
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8090
          turn:
            port: 3748
            protocol: UDP
          webrtc00:
            port: 50000
            protocol: UDP
          webrtc01:
            port: 50001
            protocol: UDP
          webrtc02:
            port: 50002
            protocol: UDP
          webrtc03:
            port: 50003
            protocol: UDP
          webrtc04:
            port: 50004
            protocol: UDP
          webrtc05:
            port: 50005
            protocol: UDP
          webrtc06:
            port: 50006
            protocol: UDP
          webrtc07:
            port: 50007
            protocol: UDP
          webrtc08:
            port: 50008
            protocol: UDP
          webrtc09:
            port: 50009
            protocol: UDP
          webrtc10:
            port: 50010
            protocol: UDP
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/icon: mdi:cctv
        hosts:
          - host: &host "ispy.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 100Mi
        mountPath: /agent/Media/XML
      media:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 2Gi
        mountPath: /agent/Media/WebServerRoot/Media
      commands:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 100Mi
        mountPath: /agent/Commands
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
